### PR TITLE
Testing the concept of having a separate aperture class for SkyCircularAperture

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by astrofrog** [comment]
I still need to test this out, but this is the concept we were discussing on the hangout. As you can see, apart from taking out the coordinate conversion code into a helper function, there's very few changes. I'd be happy to update the tests and docs if you think this seems like a good idea.

**Comment by astrofrog** [comment]
Here's an example usage:

```
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.io import fits

from photutils import aperture_photometry, SkyCircularAperture

hdu = fits.open('2MASS_k.fits.gz')[0]
gc = SkyCoord(0. * u.deg, 0 * u.deg, frame='galactic')

aperture = SkyCircularAperture(gc, r=5. * u.arcsec)
table = aperture_photometry(hdu, aperture)[0]
```

cc @cdeil @bsipocz 

If you think this seems like a good idea, I can go ahead and implement the other SkyAperture classes.

**Comment by astrofrog** [comment]
(and I can see to updating the tests and documentation)

**Comment by cdeil** [comment]
I'm not sure if this is a good or bad proposal.

A big pro is that the API for the common use case becomes really simple for the end-user.

A big con is that the definition of the region becomes problematic. Users probably expect that their `SkyCircularAperture` will correspond 1:1 to the `CircularAperture` in pixel coordinates, but that's **not true**. The difference will be negligible for most images with small FOVs, but significant for large- or all-sky images.

Another con is that we increase the number of region classes in our API and the amount of code we have to write / maintain by a factor of 2.

@nden What's the current API and timescale to become available in Astropy core for the [gWCS region](https://github.com/nden/astropy-api/blob/generalized_wcs/generalized_wcs/region_api.md) classes?
(ideally we'd just use those in photutils and get rid of the Aperture classes or make those thin wrappers around regions is needed)

**Comment by astrofrog** [comment]
@cdeil - I understand your concerns.
- regarding the definition of apertures in sky coordinates, as I mentioned yesterday, we could simply put a big caveat that we assume a constant pixel scale across the image, and that it is not suitable for large apertures. And in future there is nothing to stop us from actually supporting the sky apertures 'properly' without such an approximation.
- regarding increasing that amount of code - while I agree it doubles the classes, it does not double the lines of code - the sky apertures are a lot simpler and not much code at all.

I think it's very important that we think first of the user, even if it means more work for us. From a user API perspective, you can bet that if we don't do something like this, users will complain that they can't provide an aperture radius in arcseconds! I do think we need to support the ability to specify this, and I do understand that it complicates things a little, but at the end of the day, we are only planning on providing a very finite number of apertures. Beyond the ones we have already, I can't think of any other apart from generic polygons (and then that covers everything). So we're talking around a dozen classes max, some of them only 20 lines long.

Just a couple of ideas for improving the suggestion in this PR:
- API-wise, I think the `Sky...` classes should also take a `frame` argument to specify what frame the e.g. position angle would be taken in.
- We could allow pixel coordinates to be passed to `Sky...` (which would make `frame` default to `pixel`) and we could then rename `SkyCircularAperture` to `CircularAperture` and `CircularAperture` to `PixelCircularAperture`. The user then has a single point of entry (`CircularAperture`) and we preserve the simple `PixelCircularAperture` class as it currently is.

So example usage:

``` python
gc = SkyCoord(0. * u.deg, 0 * u.deg, frame='galactic')
aperture = CircularAperture(gc, r=5. * u.arcsec)
table = aperture_photometry(hdu, aperture)[0]

pos = ([10,20,30] * u.pixel, [50, 60, 70] * u.pixel)
aperture = CircularAperture(pos, r=5)
table = aperture_photometry(hdu, aperture)[0]
```

**Comment by cdeil** [comment]
Yes, I see that this is appealing and  I'm OK with this proposal.

I think explicit is better, so I'd prefer not to have a single point of entry `CircularAperture` class ... the user will always know if she has pixel or sky coordinates as input.
But if you really like the single entry point class way, yes, I'll work and be simple to use, so OK.

**Comment by cdeil** [comment]
(If gWCS region classes are going to land in Astropy core before the 1.0 release the end-user API is going to change anyways to use those and I'm not sure implementing this now in `photutils` as a temp solution is worth the effort.)

**Comment by astrofrog** [comment]
@cdeil - I don't think all the gWCS stuff is likely to get done for 1.0, maybe only the foundations :) I've seen other projects get held back waiting for gWCS, but I think we should just not worry too much, and do what we think is best from the user point of view. We can cross the gWCS bridge when we get there, and what we end up with can even influence the gWCS design :)

**Comment by astrofrog** [comment]
I will open a PR on master instead :)

**Comment by bsipocz** [comment]
I'm sorry not checking this sooner, I was offline due to some on site electrical testing....

**Pull request closed without merging**
